// @title			Uptime Lite API
// @version		1.0
// @description	Distributed HTTP uptime monitoring service.
// @contact.name	API Support
// @license.name	MIT
// @host			localhost:8080
// @BasePath		/
// @schemes		http https
package main

import (
	"context"
	"errors"
	"log"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"uptime-lite/internal/api"
	"uptime-lite/internal/cache"
	"uptime-lite/internal/config"
	"uptime-lite/internal/db"
	"uptime-lite/internal/repository"
	"uptime-lite/internal/worker"

	_ "uptime-lite/docs" // generated by swag init
)

func main() {
	// ── Configuration ──────────────────────────────────────────────────────────
	cfg, err := config.Load()
	if err != nil {
		log.Fatalf("config: %v", err)
	}

	// ── PostgreSQL ─────────────────────────────────────────────────────────────
	pgPool, err := db.Connect(cfg.DatabaseURL)
	if err != nil {
		log.Fatalf("postgres: %v", err)
	}
	defer pgPool.Close()

	if err := db.Migrate(pgPool); err != nil {
		log.Fatalf("migrate: %v", err)
	}
	log.Println("postgres: connected and migrated")

	// ── Redis ──────────────────────────────────────────────────────────────────
	redisClient, err := cache.New(cfg.RedisURL)
	if err != nil {
		log.Fatalf("redis: %v", err)
	}
	defer redisClient.Close()
	log.Println("redis: connected")

	// ── Domain layer ───────────────────────────────────────────────────────────
	repo := repository.New(pgPool)

	// ── Worker pool ────────────────────────────────────────────────────────────
	// ctx controls the lifetime of all background goroutines.
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	pool := worker.NewPool(cfg.WorkerCount, repo, redisClient)
	pool.Start(ctx)
	log.Printf("worker pool: %d workers started", cfg.WorkerCount)

	// ── HTTP server ────────────────────────────────────────────────────────────
	router := api.NewRouter(repo, redisClient)
	srv := &http.Server{
		Addr:         ":" + cfg.Port,
		Handler:      router,
		ReadTimeout:  15 * time.Second,
		WriteTimeout: 15 * time.Second,
		IdleTimeout:  60 * time.Second,
	}

	go func() {
		log.Printf("http: listening on :%s", cfg.Port)
		if err := srv.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
			log.Fatalf("http: %v", err)
		}
	}()

	// ── Graceful shutdown ──────────────────────────────────────────────────────
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit
	log.Println("shutdown signal received")

	// 1. Stop accepting new HTTP requests (10 s deadline for in-flight requests).
	shutdownCtx, shutdownCancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer shutdownCancel()
	if err := srv.Shutdown(shutdownCtx); err != nil {
		log.Printf("http shutdown: %v", err)
	}

	// 2. Cancel workers and wait for them to finish their current check cycle.
	cancel()
	pool.Wait()

	log.Println("shutdown complete")
}
